export const STATUS_LABELS = {
  again: "再来一次",
  hard: "困难",
  good: "掌握",
  easy: "轻松",
};

export const MOCK_STATE = {
  connected: false,
  runtime: { mode: "demo", contextScanEnabled: false },
  goal: {
    statement: "把我日常正在做的事，用英语表达出来",
    successDefinition: "遇到熟悉的工作和生活场景时，能直接调用合适的英文表达，而不是逐句翻译",
  },
  summary: "你正在与团队讨论一款面向全球用户的健康饮食产品，涉及功能设计、目标用户、产品价值和市场策略。我从这个上下文中提取了 5 个现在最可能用得上的英语表达。",
  focusPoints: [
    "介绍产品的核心功能和使用场景",
    "说明如何根据饮食偏好提供个性化建议",
    "讨论产品的长期价值和功能优先级",
  ],
  dueCount: 0,
  reviewQueue: [],
  contextIndex: {
    indexedAt: null,
    activeTopicId: "food-health",
    coverage: {
      mode: "demo",
      discoveredTaskCount: 2,
      titledTaskCount: 2,
      deepAnalyzedTaskCount: 0,
      fullContentScannedTaskCount: 0,
      contentBytesIndexed: 0,
      newOrChangedTaskCount: 0,
      reusedContentTaskCount: 0,
      metadataCoveragePercent: 100,
      scope: "演示任务，不代表真实 Codex 历史",
      rawContentStored: false,
    },
    topics: [
      { id: "food-health", label: "FoodLink 与健康饮食产品", focus: "饮食产品、识别能力、健康建议与用户价值", taskCount: 1, deepAnalyzedCount: 0, candidateCount: 5, recentTitles: ["健康产品演示任务"] },
      { id: "embodied-ai", label: "具身智能与机器人", focus: "比赛任务、机器人感知、抓取方案、实验结果与下一步改进", taskCount: 1, deepAnalyzedCount: 0, candidateCount: 0, recentTitles: ["具身智能比赛演示任务"] },
    ],
    tasks: [
      { id: "demo-food", title: "健康产品演示任务", topicId: "food-health", topicLabel: "FoodLink 与健康饮食产品", deepAnalyzed: false },
      { id: "demo-robot", title: "具身智能比赛演示任务", topicId: "embodied-ai", topicLabel: "具身智能与机器人", deepAnalyzed: false },
    ],
  },
  library: {
    title: "生活英语起步词库",
    description: "基础词、短语和生活场景表达；每次只从储备池挑少量内容进入学习。",
    entryCount: 540,
    resultCount: 12,
    levels: ["A1", "A2", "B1"],
    scenarios: [
      { id: "social", label: "社交问候" }, { id: "home", label: "居家日常" },
      { id: "food", label: "餐饮与厨房" }, { id: "shopping", label: "购物与支付" },
      { id: "transport", label: "交通与问路" }, { id: "work", label: "工作与办公" },
    ],
    entries: [
      { id: "mock-hello", term: "hello", meaning: "你好", kind: "word", level: "A1", scenario_ids: ["social"], scenario_labels: ["社交问候"], target_modes: ["recognition", "production"], status: "available" },
      { id: "mock-please", term: "please", meaning: "请", kind: "word", level: "A1", scenario_ids: ["social"], scenario_labels: ["社交问候"], target_modes: ["recognition", "production"], status: "available" },
      { id: "mock-water", term: "water", meaning: "水", kind: "word", level: "A1", scenario_ids: ["food"], scenario_labels: ["餐饮与厨房"], target_modes: ["recognition", "production"], status: "available" },
      { id: "mock-kitchen", term: "kitchen", meaning: "厨房", kind: "word", level: "A1", scenario_ids: ["home"], scenario_labels: ["居家日常"], target_modes: ["recognition", "production"], status: "available" },
      { id: "mock-price", term: "price", meaning: "价格", kind: "word", level: "A1", scenario_ids: ["shopping"], scenario_labels: ["购物与支付"], target_modes: ["recognition", "production"], status: "available" },
      { id: "mock-bus", term: "bus", meaning: "公共汽车", kind: "word", level: "A1", scenario_ids: ["transport"], scenario_labels: ["交通与问路"], target_modes: ["recognition", "production"], status: "available" },
      { id: "mock-take-care", term: "take care", meaning: "保重；当心", kind: "phrase", level: "A2", scenario_ids: ["social"], scenario_labels: ["社交问候"], target_modes: ["recognition", "production"], status: "available" },
      { id: "mock-try-on", term: "try on", meaning: "试穿", kind: "phrase", level: "A2", scenario_ids: ["shopping"], scenario_labels: ["购物与支付"], target_modes: ["recognition", "production"], status: "available" },
      { id: "mock-get-off", term: "get off", meaning: "下车", kind: "phrase", level: "A2", scenario_ids: ["transport"], scenario_labels: ["交通与问路"], target_modes: ["recognition", "production"], status: "available" },
      { id: "mock-follow-up", term: "follow up", meaning: "跟进", kind: "phrase", level: "B1", scenario_ids: ["work"], scenario_labels: ["工作与办公"], target_modes: ["recognition", "production"], status: "available" },
      { id: "mock-in-advance", term: "in advance", meaning: "提前", kind: "phrase", level: "B1", scenario_ids: ["work"], scenario_labels: ["工作与办公"], target_modes: ["recognition", "production"], status: "available" },
      { id: "mock-make-progress", term: "make progress", meaning: "取得进展", kind: "phrase", level: "B1", scenario_ids: ["work"], scenario_labels: ["工作与办公"], target_modes: ["recognition", "production"], status: "available" },
    ],
  },
  candidates: [
    { id: "demo-estimate", term: "estimate portion sizes", meaning: "估算食物的分量大小", rationale: "你在讨论产品的饮食建议功能时提到这个场景，未来需要向用户解释如何使用。", sourceLabel: "当前项目讨论", sourceTime: "刚刚", mode: "production", modeLabel: "主动表达", status: "proposed", anchor: "介绍产品如何分析一张真实的餐食照片。" },
    { id: "demo-dietary", term: "dietary preferences", meaning: "饮食偏好；饮食习惯", rationale: "你多次提到根据用户的饮食偏好提供个性化方案，这是产品的核心功能之一。", sourceLabel: "当前项目讨论", sourceTime: "刚刚", mode: "production", modeLabel: "主动表达", status: "proposed", anchor: "对比两个用户不同的饮食需求。" },
    { id: "demo-prioritize", term: "prioritize", meaning: "优先考虑；把……放在优先位置", rationale: "你在讨论产品路线图时提到需要优先考虑高频用户需求，并在英文讨论中多次使用。", sourceLabel: "当前项目讨论", sourceTime: "刚刚", mode: "production", modeLabel: "主动表达", status: "proposed", anchor: "向团队解释为什么先开发一个小功能。" },
    { id: "demo-seamless", term: "seamless experience", meaning: "无缝的体验；流畅的使用体验", rationale: "你希望在产品介绍中突出简单、顺畅的使用体验，这个表达在对话中被多次提及。", sourceLabel: "当前项目讨论", sourceTime: "刚刚", mode: "production", modeLabel: "主动表达", status: "proposed", anchor: "描述用户拍照后立即得到结果的过程。" },
    { id: "demo-long-run", term: "in the long run", meaning: "从长远来看；长期而言", rationale: "你在讨论产品价值时提到它能在长期内帮助用户养成更健康的饮食习惯。", sourceLabel: "当前项目讨论", sourceTime: "刚刚", mode: "recognition", modeLabel: "理解优先", status: "proposed", anchor: "说明产品长期带来的用户价值。" },
  ],
  sources: [
    { id: "current-project-chat", label: "当前项目讨论", kind: "current_conversation", status: "active", summary: "关于健康饮食产品功能、用户价值与路线图的授权对话摘要。" },
  ],
};

const mockContextEntries = MOCK_STATE.candidates.map((entry) => ({
  id: entry.id,
  candidateId: entry.id,
  lexiconEntryId: null,
  term: entry.term,
  meaning: entry.meaning,
  kind: "phrase",
  level: "",
  scenarioIds: [],
  scenarioLabels: [],
  contextIds: ["food-health"],
  contextLabels: ["FoodLink 与健康饮食产品"],
  taskCount: 1,
  recentTitles: ["健康产品演示任务"],
  sourceType: "contextual",
  status: entry.status,
  targetModes: [entry.mode],
}));

const mockFoundationEntries = MOCK_STATE.library.entries.map((entry) => ({
  id: entry.id,
  candidateId: null,
  lexiconEntryId: entry.id,
  term: entry.term,
  meaning: entry.meaning,
  kind: entry.kind,
  level: entry.level,
  scenarioIds: entry.scenario_ids,
  scenarioLabels: entry.scenario_labels,
  contextIds: [],
  contextLabels: [],
  taskCount: 0,
  recentTitles: [],
  sourceType: "foundation",
  status: entry.status,
  targetModes: entry.target_modes,
}));

MOCK_STATE.personalVocabulary = {
  title: "我的英语词表",
  description: "演示词表",
  entryCount: mockContextEntries.length + mockFoundationEntries.length,
  uniqueTermCount: new Set([...mockContextEntries, ...mockFoundationEntries].map((entry) => entry.term.toLocaleLowerCase())).size,
  contextualCount: mockContextEntries.length,
  observedCount: 0,
  foundationCount: mockFoundationEntries.length,
  contexts: MOCK_STATE.contextIndex.topics.map((topic) => ({ id: topic.id, label: topic.label, wordCount: topic.candidateCount })),
  levels: MOCK_STATE.library.levels,
  entries: [...mockContextEntries, ...mockFoundationEntries],
  updatedAt: null,
  coverage: MOCK_STATE.contextIndex.coverage,
};
